name: CI

on:
  push:
    branches:
    - master
  pull_request: {}

jobs:
  build:
    # With ubuntu-latest (20.04), some tests using self signed SSL cert suddenly failed at version 20210614.1.
    # The issue may be fixed later, but I'll use ubuntu-18.04 for a while as a workaround.
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java_version: [8, 11]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java_version }}
    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-${{ matrix.java_version }}-gradle-${{ hashFiles('**/*.gradle*') }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run tests
      run: ./gradlew check jacocoTestReport coveralls --stacktrace --info

  # Fluency uses java.nio.ByteBuffer which can cause inconsistent method signature issue between JDK 8 and 9.
  # We've created Fluency jars using JDK 8 for that and we need to confirm an application built with JDK 9 or later
  # can use Fluecy jars built with JDK 8 without any problem.
  prepare_for_integration_test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-8-gradle-${{ hashFiles('**/*.gradle*') }}
    - name: Install local maven package
      run: |
        ./gradlew publishToMavenLocal --stacktrace --info
    - name: Upload local Maven package just installed
      uses: actions/upload-artifact@v3
      with:
        name: local-m2
        path: ~/.m2

  integration_test:
    runs-on: ubuntu-18.04
    needs: prepare_for_integration_test
    strategy:
      matrix:
        java_version: [8, 11]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java_version }}
    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-${{ matrix.java_version }}-gradle-${{ hashFiles('**/*.gradle*') }}
    - name: Download local Maven package prepared above
      uses: actions/download-artifact@v3
      with:
        name: local-m2
    - name: Run tests using real Fluentd
      run: |
        sudo gem install yajl-ruby --no-doc -v 1.4.1
        sudo gem install fluentd --no-doc
        echo "127.0.0.1 my-server" | sudo tee -a /etc/hosts
        cd tests/mutual-tls && ./run.sh

